HOST=$1
ACCOUNT=$2
PASSWORD=$3
OUTPUTPATH=$4

echo "TERADATA DDL Extraction Sample Script"
echo "======================================"
echo "This script connects to your Teradata Server and extracts the DDLS for "
echo "tables,views,join indexes, functions, procedures and macros "
echo "Usage: ./create_ddls.sh HOST ACCOUNT PASSWORD OUTPUTPATH"

. ./create_ddls_config.sh

bteq <<EOF > ddl_extraction.log
.LOGON $HOST/$ACCOUNT,$PASSWORD;

**** CREATE TABLES FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Tables.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-table> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ' </sc-table> */'' as "--";     ' || 'SHOW TABLE ' || TRIM(T1.DATABASENAME) || '.' ||TRIM(T1.TABLENAME) || ';' "--" FROM DBC.TABLESV T1 WHERE T1.TABLEKIND IN ('T','O','Q') AND (UPPER(T1.DATABASENAME) IN (${DBS_TABLES})) AND (UPPER(T1.TABLENAME) LIKE ANY (${TABLES_INCLUDE}))  GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Tables.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Tables.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Tables.sql
.EXPORT RESET


**** CREATE JOIN INDEXES FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Join_Indexes.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-joinindex> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ' </sc-joinindex> */'' as "--";     ' || 'SHOW JOIN INDEX ' || TRIM(T1.DATABASENAME) || '.' ||TRIM(T1.TABLENAME) || ';' "--" FROM DBC.TABLESV T1 WHERE T1.TABLEKIND IN ('I') AND (UPPER(T1.DATABASENAME) IN (${DBS_JOININDEX})) AND (UPPER(T1.TABLENAME) LIKE ANY (${JOININDEX_INCLUDE})) GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Join_Indexes.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Join_Indexes.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Join_Indexes.sql
.EXPORT RESET


**** CREATE VIEWS FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Views.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-view> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ' </sc-view> */'' as "--";     ' || 'SHOW VIEW ' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ';' "--" FROM DBC.TABLESV T1 WHERE T1.TABLEKIND = 'V' AND (UPPER(T1.DATABASENAME) IN ($DBS_VIEWS)) AND (UPPER(T1.DATABASENAME) NOT IN ($DBS_TABLES_EXCLUDE)) AND (UPPER(T1.TABLENAME) LIKE ANY ($TABLES_INCLUDE)) GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Views.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Views.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Views.sql
.EXPORT RESET

**** CREATE FUNCTIONS FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Functions.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-function> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.SpecificNAME) || ' <sc-function> */'' as "--";   ' || 'SHOW FUNCTION ' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.FUNCTIONNAME) || ';' "--" FROM DBC.FUNCTIONSV T1 WHERE (UPPER(T1.DATABASENAME) IN ($DBS_FUNCTIONS)) GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Functions.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Functions.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Functions.sql
.EXPORT RESET

**** CREATE MACROS FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Macros.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-macro> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ' </sc-macro> */'' as "--";     ' || 'SHOW MACRO ' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ';' "--" FROM DBC.TABLESV T1 WHERE T1.TABLEKIND = 'M' AND (UPPER(T1.DATABASENAME) IN ($DBS_MACROS)) AND (UPPER(T1.TABLENAME) LIKE ANY ($MACROS_INCLUDE)) GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Macros.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Macros.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Macros.sql
.EXPORT RESET


**** CREATE PROCEDURES FILE ****
.EXPORT FILE = $OUTPUTPATH/SHOW_Procedures.sql
.SET WIDTH 65531
SELECT 'SELECT ''/* <sc-procedure> '' || ''' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ' </sc-procedure> */'' as "--";     ' || 'SHOW PROCEDURE ' || TRIM(T1.DATABASENAME) || '.' || TRIM(T1.TABLENAME) || ';' "--" FROM DBC.TABLESV T1 WHERE T1.TABLEKIND = 'P' AND (UPPER(T1.DATABASENAME) IN ($DBS_PROCEDURES)) AND (UPPER(T1.TABLENAME) LIKE ANY ($PROCEDURES_INCLUDE)) GROUP BY 1; 
.EXPORT RESET
.OS rm $OUTPUTPATH/DDL_Procedures.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Procedures.sql
.SET WIDTH 65531
.RUN FILE = $OUTPUTPATH/SHOW_Procedures.sql
.EXPORT RESET


**** CREATE DATABASES FILE ****
.OS rm $OUTPUTPATH/DDL_Databases.sql
.EXPORT FILE = $OUTPUTPATH/DDL_Databases.sql
.SET WIDTH 65531
SELECT 'CREATE DATABASE ' || TRIM(T1.DATABASENAME) || ' FROM DBC AS PERM = 100000000;' "--" FROM DBC.DATABASESV T1 WHERE (UPPER(T1.DATABASENAME) IN ($DBS)) GROUP BY 1 ORDER BY 1;
.EXPORT RESET


**** CREATE SNOWFLAKE SCHEMA FILE ****
.OS rm $OUTPUTPATH/DDL_SF_Schemas.sql
.EXPORT FILE = $OUTPUTPATH/DDL_SF_Schemas.sql
.SET WIDTH 65531
SELECT  '/* <sc-schema> ' ||  TRIM(T1.DATABASENAME) || '</sc-schema> */      ' ||  'CREATE SCHEMA ' || TRIM(T1.DATABASENAME) || ';' "--" FROM DBC.DATABASESV T1 WHERE (UPPER(T1.DATABASENAME) IN ($DBS)) GROUP BY 1 ORDER BY 1;
.EXPORT RESET


.quit 0;

EOF